version: 0.2

batch:
  fast-fail: true
phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - cd Backend
      - npm i --force
      - tsc --project tsconfig.json
  post_build:
    commands:
        - echo "post-build"
        - cp -R node_modules/ dist/
artifacts:
  type: zip
  files:
    - "**/*"
  base-directory: build
