version: 0.2

batch:
  fast-fail: true
phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - cd backend
      - npm run build
  post_build:
    commands:
        - cp -R node_modules/ dist/node_modules
artifacts:
  type: zip
  files:
    - "**/*"
  base-directory: build
